<a href="https://colab.research.google.com/github/SThakur47/Food-Donation/blob/main/chapter_appendix-tools-for-deep-learning/jupyter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Using Jupyter Notebooks
:label:`sec_jupyter`


This section describes how to edit and run the code
in each section of this book
using the Jupyter Notebook. Make sure you have
installed Jupyter and downloaded the
code as described in
:ref:`chap_installation`.
If you want to know more about Jupyter see the excellent tutorial in
their [documentation](https://jupyter.readthedocs.io/en/latest/).


## Editing and Running the Code Locally

Suppose that the local path of the book's code is `xx/yy/d2l-en/`. Use the shell to change the directory to this path (`cd xx/yy/d2l-en`) and run the command `jupyter notebook`. If your browser does not do this automatically, open http://localhost:8888 and you will see the interface of Jupyter and all the folders containing the code of the book, as shown in :numref:`fig_jupyter00`.

![The folders containing the code of this book.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter00.png?raw=1)
:width:`600px`
:label:`fig_jupyter00`


You can access the notebook files by clicking on the folder displayed on the webpage.
They usually have the suffix ".ipynb".
For the sake of brevity, we create a temporary "test.ipynb" file.
The content displayed after you click it is
shown in :numref:`fig_jupyter01`.
This notebook includes a markdown cell and a code cell. The content in the markdown cell includes "This Is a Title" and "This is text.".
The code cell contains two lines of Python code.

![Markdown and code cells in the "text.ipynb" file.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter01.png?raw=1)
:width:`600px`
:label:`fig_jupyter01`


Double click on the markdown cell to enter edit mode.
Add a new text string "Hello world." at the end of the cell, as shown in :numref:`fig_jupyter02`.

![Edit the markdown cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter02.png?raw=1)
:width:`600px`
:label:`fig_jupyter02`


As demonstrated in :numref:`fig_jupyter03`,
click "Cell" $\rightarrow$ "Run Cells" in the menu bar to run the edited cell.

![Run the cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter03.png?raw=1)
:width:`600px`
:label:`fig_jupyter03`

After running, the markdown cell is shown in :numref:`fig_jupyter04`.

![The markdown cell after running.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter04.png?raw=1)
:width:`600px`
:label:`fig_jupyter04`


Next, click on the code cell. Multiply the elements by 2 after the last line of code, as shown in :numref:`fig_jupyter05`.

![Edit the code cell.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter05.png?raw=1)
:width:`600px`
:label:`fig_jupyter05`


You can also run the cell with a shortcut ("Ctrl + Enter" by default) and obtain the output result from :numref:`fig_jupyter06`.

![Run the code cell to obtain the output.](https://github.com/d2l-ai/d2l-en-colab/blob/master/img/jupyter06.png?raw=1)
:width:`600px`
:label:`fig_jupyter06`


When a notebook contains more cells, we can click "Kernel" $\rightarrow$ "Restart & Run All" in the menu bar to run all the cells in the entire notebook. By clicking "Help" $\rightarrow$ "Edit Keyboard Shortcuts" in the menu bar, you can edit the shortcuts according to your preferences.

## Advanced Options

Beyond local editing two things are quite important: editing the notebooks in the markdown format and running Jupyter remotely.
The latter matters when we want to run the code on a faster server.
The former matters since Jupyter's native ipynb format stores a lot of auxiliary data that is
irrelevant to the content,
mostly related to how and where the code is run.
This is confusing for Git, making
reviewing contributions very difficult.
Fortunately there is an alternative---native editing in the markdown format.

### Markdown Files in Jupyter

If you wish to contribute to the content of this book, you need to modify the
source file (md file, not ipynb file) on GitHub.
Using the notedown plugin we
can modify notebooks in the md format directly in Jupyter.


First, install the notedown plugin, run the Jupyter Notebook, and load the plugin:

```
pip install d2l-notedown  # You may need to uninstall the original notedown.
jupyter notebook --NotebookApp.contents_manager_class='notedown.NotedownContentsManager'
```

You may also turn on the notedown plugin by default whenever you run the Jupyter Notebook.
First, generate a Jupyter Notebook configuration file (if it has already been generated, you can skip this step).

```
jupyter notebook --generate-config
```

Then, add the following line to the end of the Jupyter Notebook configuration file (for Linux or macOS, usually in the path `~/.jupyter/jupyter_notebook_config.py`):

```
c.NotebookApp.contents_manager_class = 'notedown.NotedownContentsManager'
```

After that, you only need to run the `jupyter notebook` command to turn on the notedown plugin by default.

### Running Jupyter Notebooks on a Remote Server

Sometimes, you may want to run Jupyter notebooks on a remote server and access it through a browser on your local computer. If Linux or macOS is installed on your local machine (Windows can also support this function through third-party software such as PuTTY), you can use port forwarding:

```
ssh myserver -L 8888:localhost:8888
```

The above string `myserver` is the address of the remote server.
Then we can use http://localhost:8888 to access the remote server `myserver` that runs Jupyter notebooks. We will detail on how to run Jupyter notebooks on AWS instances
later in this appendix.

### Timing

We can use the `ExecuteTime` plugin to time the execution of each code cell in Jupyter notebooks.
Use the following commands to install the plugin:

```
pip install jupyter_contrib_nbextensions
jupyter contrib nbextension install --user
jupyter nbextension enable execute_time/ExecuteTime
```

## Summary

* Using the Jupyter Notebook tool, we can edit, run, and contribute to each section of the book.
* We can run Jupyter notebooks on remote servers using port forwarding.


## Exercises

1. Edit and run the code in this book with the Jupyter Notebook on your local machine.
1. Edit and run the code in this book with the Jupyter Notebook *remotely* via port forwarding.
1. Compare the running time of the operations $\mathbf{A}^\top \mathbf{B}$ and $\mathbf{A} \mathbf{B}$ for two square matrices in $\mathbb{R}^{1024 \times 1024}$. Which one is faster?


[Discussions](https://discuss.d2l.ai/t/421)

In [2]:
import numpy as np

a= np.array([1,2,3,4,5])
print(a)
# which type of  array
print(a.dtype)

# type of class a having
print(type(a))

[1 2 3 4 5]
int64
<class 'numpy.ndarray'>

In [8]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [9]:
print("-----------------------")

shape=(3,2)

np.ones(shape)

-----------------------

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.array([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.array([[1,2,3],[4,"5",6],[7,8,9]])

array([['1', '2', '3'],
       ['4', '5', '6'],
       ['7', '8', '9']], dtype='<U21')

In [16]:
import pandas as pd


pd.Series([12,3,4])

0    12
1     3
2     4
dtype: int64

In [17]:
import pandas as pd


pd.Series([12,3,4], index=[2,3,4])

2    12
3     3
4     4
dtype: int64

In [18]:
import pandas as pd


pd.Series([12,3,4], index=["Ram","aman","karan"])

Ram      12
aman      3
karan     4
dtype: int64

In [26]:
d={"No. of rooms": [3,4,5],"sqfeet":[567,654,794],"price":[60000,700000,80000]}
print(d)

print("--------------------")
z=pd.DataFrame(d)
z.info()

{'No. of rooms': [3, 4, 5], 'sqfeet': [567, 654, 794], 'price': [60000, 700000, 80000]}
--------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   No. of rooms  3 non-null      int64
 1   sqfeet        3 non-null      int64
 2   price         3 non-null      int64
dtypes: int64(3)
memory usage: 204.0 bytes

In [28]:
file1=pd.read_csv("/content/insurance.csv")
print(file1)

       age  gender    bmi  children  smoker     region      charges
0      NaN  female  27.90         0       1  southwest  16884.92400
1      NaN    male  33.77         1       0  southeast   1725.55230
2     28.0    male  33.00         3       0  southeast   4449.46200
3     33.0    male    NaN         0       0  northwest  21984.47061
4     32.0    male    NaN         0       0  northwest   3866.85520
...    ...     ...    ...       ...     ...        ...          ...
1333  50.0    male  30.97         3       0  northwest  10600.54830
1334  18.0  female  31.92         0       0  northeast   2205.98080
1335  18.0  female  36.85         0       0  southeast   1629.83350
1336  21.0  female  25.80         0       0  southwest   2007.94500
1337  61.0  female  29.07         0       1  northwest  29141.36030

[1338 rows x 7 columns]

In [30]:
print(file1.head(10))
# first 10 record

    age  gender    bmi  children  smoker     region      charges
0   NaN  female  27.90         0       1  southwest  16884.92400
1   NaN    male  33.77         1       0  southeast   1725.55230
2  28.0    male  33.00         3       0  southeast   4449.46200
3  33.0    male    NaN         0       0  northwest  21984.47061
4  32.0    male    NaN         0       0  northwest   3866.85520
5   NaN  female  25.74         0       0  southeast   3756.62160
6  46.0  female  33.44         1       0  southeast   8240.58960
7  37.0  female  27.74         3       0  northwest   7281.50560
8  37.0    male  29.83         2       0  northeast   6406.41070
9  60.0  female  25.84         0       0  northwest  28923.13692

In [31]:
print(file1.tail(10))
# last 10 record

       age  gender     bmi  children  smoker     region      charges
1328  23.0  female  24.225         2       0  northeast  22395.74424
1329  52.0    male  38.600         2       0  southwest  10325.20600
1330  57.0  female  25.740         2       0  southeast  12629.16560
1331  23.0  female  33.400         0       0  southwest  10795.93733
1332  52.0  female  44.700         3       0  southwest  11411.68500
1333  50.0    male  30.970         3       0  northwest  10600.54830
1334  18.0  female  31.920         0       0  northeast   2205.98080
1335  18.0  female  36.850         0       0  southeast   1629.83350
1336  21.0  female  25.800         0       0  southwest   2007.94500
1337  61.0  female  29.070         0       1  northwest  29141.36030

In [32]:
z=file1.head(10)

# download a file with first 10 record
z.to_excel("file_first.xlsx")